export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const LOGOUT = 'LOGOUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';

// Clubs
export const REQUEST_CLUBS = 'REQUEST_CLUBS';
export const RECEIVE_CLUBS = 'RECEIVE_CLUBS';
export const REQUEST_MEMBERS = 'REQUEST_MEMBERS';
export const RECEIVE_MEMBERS = 'RECEIVE_MEMBERS';
export const RECEIVE_CLUB_NAME = 'RECEIVE_CLUB_NAME';
export const RECEIVE_CLUB_INFO = 'RECEIVE_CLUB_INFO';
export const DELETE_CLUB_SUCCESS = 'DELETE_CLUB_SUCCESS';

// User - Already read books
export const REQUEST_MEMBER_ALREADY_READ_BOOKS = 'REQUEST_MEMBER_ALREADY_READ_BOOKS';
export const RECEIVE_MEMBER_ALREADY_READ_BOOKS = 'RECEIVE_MEMBER_ALREADY_READ_BOOKS';
// User - want to read books
export const REQUEST_MEMBER_WANT_TO_READ_BOOKS = 'REQUEST_MEMBER_WANT_TO_READ_BOOKS';
export const RECEIVE_MEMBER_WANT_TO_READ_BOOKS = 'RECEIVE_MEMBER_WANT_TO_READ_BOOKS';

// Messages
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

// Meetings
export const REQUEST_MEETINGS = 'REQUEST_MEETINGS';
export const RECEIVE_MEETINGS = 'RECEIVE_MEETINGS';

// Memberships
export const REQUEST_MEMBERSHIPS = 'REQUEST_MEMBERSHIPS';
export const RECEIVE_MEMBERSHIPS = 'RECEIVE_MEMBERSHIPS';
export const CHECK_MEMBERSHIPS_BY_USERID = 'CHECK_MEMBERSHIPS_BY_USERID';

// Clubs - Setting
export const MERGE_MEMBERSHIP_BY_USERID = 'MERGE_MEMBERSHIP_BY_USERID';
export const CHECK_CLUB_ADMIN = 'CHECK_CLUB_ADMIN';
export const REMOVE_MEMBERSHIP = 'REMOVE_MEMBERSHIP';
export const RECEIVE_MEMBER_STATUS = 'RECEIVE_MEMBER_STATUS';

// Book inspiration
export const REQUEST_BOOK_INSPIRATION = 'REQUEST_BOOK_INSPIRATION';
export const RECEIVE_BOOK_INSPIRATION = 'RECEIVE_BOOK_INSPIRATION';

// Clubs - Book We've read
export const REQUEST_ALREADY_READ_BOOKS = 'REQUEST_ALREADY_READ_BOOKS';
export const RECEIVE_ALREADY_READ_BOOKS = 'RECEIVE_ALREADY_READ_BOOKS';

export const RSVP_SUCCESS = 'RSVP_SUCCESS';

export const DELETE_ALREADY_READ_BOOK = 'DELETE_ALREADY_READ_BOOK';
export const DELETE_ALREADY_READ_BOOK_SUCCESS = 'DELETE_ALREADY_READ_BOOK_SUCCESS';
export const DELETE_ALREADY_READ_BOOK_FAILURE = 'DELETE_ALREADY_READ_BOOK_FAILURE';

// Polls
export const POLLS_CREATE = 'POLLS_CREATE';
export const POLLS_CREATE_SUCCESS = 'POLLS_CREATE_SUCCESS';
export const POLLS_CREATE_ERROR = 'POLLS_CREATE_ERROR';
export const POLLS_REQUEST = 'POLLS_REQUEST';
export const POLLS_RECEIVE = 'POLLS_RECEIVE';
export const POLLS_UPDATE = 'POLLS_UPDATE';
export const POLLS_UPDATE_SUCCESS = 'POLLS_UPDATE_SUCCESS';
export const POLLS_UPDATE_ERROR = 'POLLS_UPDATE_ERROR';
export const POLLS_DELETE = 'POLLS_DELETE';
export const POLLS_DELETE_SUCCESS = 'POLLS_DELETE_SUCCESS';
export const POLLS_DELETE_ERROR = 'POLLS_DELETE_ERROR';

export const POLLS_VOTE_DATE_TIME = 'POLLS_VOTE_DATE_TIME';
export const POLLS_VOTE_DATE_TIME_SUCCESS = 'POLLS_VOTE_DATE_TIME_SUCCESS';
export const POLLS_VOTE_DATE_TIME_ERROR = 'POLLS_VOTE_DATE_TIME_ERROR';

export const POLLS_VOTE_BOOK = 'POLLS_VOTE_BOOK';
export const POLLS_VOTE_BOOK_SUCCESS = 'POLLS_VOTE_BOOK_SUCCESS';
export const POLLS_VOTE_BOOK_ERROR = 'POLLS_VOTE_BOOK_ERROR';
